### ISSUE TITLE
Migrate from moment to date-fns

### ISSUE THREAD

**Issue by janczizikow** [cara-care/dashboard#10]
Remove [moment.js](https://momentjs.com/) dependency and use [date-fns](https://date-fns.org/) instead. Moment is great but date-fns is 3.9 times [smaller](https://bundlephobia.com/result?p=date-fns@2.11.1) and [more performant](https://medium.com/@k2u4yt/momentjs-vs-date-fns-6bddc7bfa21e). Also requires to change the library of [material-ui-pickers](https://material-ui-pickers.dev/getting-started/installation#peer-library).

**Comment by bengry** [comment]
@janczizikow I'd like to work on this if possible.

**Comment by bengry** [comment]
@janczizikow I opened #30 that closes this issue.

Also, I'd appreciate it if you could add the `hacktoberfest` topic to this repo so this PR will be eligible for it. [Due to some recent spamming, Hacktoberfest is now opt-in for repositories](https://hacktoberfest.digitalocean.com/hacktoberfest-update), if you decide to merge/accept it.

**Comment by janczizikow** [comment]
Hey @bengry thanks a lot! I left some comments on the PR and opted-in this repo to Hacktoberfest.
